### ISSUE TITLE
use supervisor

### ISSUE THREAD

**Issue by ayrat555** [kirqe/el_meduza#2]
use supervisor for process management

**Comment by kirqe** [comment]
With genserver or just by adding [ application.ex](https://github.com/kirqe/el_meduza/blob/master/lib/application.ex) with supervisor initialisation? 

Sorry, new to elixir :)
Thanks for feedback

**Comment by ayrat555** [comment]
@kirqe yep, what you did is exactly what I meant. Good work!

I'd recommend reading 'Elixir in Action' by Sasa Juric. It has good introduction to OTP stuff.
