### ISSUE TITLE
add dialyzer

### ISSUE THREAD

**Issue by ayrat555** [kirqe/el_meduza#4]
it's cool that you added typespecs but there is no dialyzer in your deps to verify them

**Comment by kirqe** [comment]
I added them only for docs purpose.
eg
<img width="333" alt="screen shot 2017-10-23 at 16 09 24" src="https://user-images.githubusercontent.com/5272402/31890683-aa70470e-b80c-11e7-8549-edd85f45bc40.png">

https://elixirforum.com/t/is-dialyzer-worth-the-effort/4814/2

Added dialyzer
<sub><sup>But this seems to be overkill for this kind of package :)</sub></sup>
